### ISSUE TITLE
Dataset Link

### ISSUE THREAD

**Issue by DachunKai** [eventbasedvision/eTraM#2]
Fantastic work! Could you provide the download link for the complete eTraM dataset? If it hasn't been uploaded yet, when will the dataset be available to the public?

**Comment by eventbasedvision** [comment]
Hi Dachunkai, Dataset will be made available by 15th April 2024
Thanks.

**Comment by aayush-v** [comment]
Hi @DachunKai the dataset is available. Closing this issue, do let us know if you face any issues. Thanks.
